version: "3.9"

services:
  web:
    build: ./web
    container_name: web
    restart: always
    env_file:
      - ./web/env.dev
    expose:
      - 8080
    networks:
      - flask-network
    depends_on:
      - db
     
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - flask-network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./web/env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - flask-network
    expose:
      - 5432

networks:
  flask-network:

volumes:
  db_data:
